### PR TITLE
Add a matrix to the options. Use this matrix in the shader.

### PR DESCRIPTION
**Pull request by ufenegga**
If no matrix are passed, we use an identity matrix.

This can be useful when you use a canvas layer in a mapping library. I am using leaflet, and 
i update the matrix and render each time the user zooms/pans, so the raster is correct.

### CODE REVIEW

**Comment by ufenegga** [comment]
Hi.. i forget to put a bit of context : i am playing with mapping, raster files, and webGL. I am making a small project that use a leaflet and some raster files, so i am exploring GeoTiff and plotty..

Back to my PR, i think putting the matrix as a global options is not the best.. i think if you have multiple datasets, you should have a matrix associated with each dataset. Then you could render multiple datasets on the same map...

**Comment by santilland** [comment]
Hello ufenegga, sorry for the late reaction, sadly i could not get to work on this for a while.
First of all, thank you for your PR! The possibility to apply a transformation matrix is very nice! If i understand correctly you still think it could be improved a little using a matrix for each dataset?
I think for now the option is quite nice and as it is optional i see no problem merging it, if i hear no objections from you i will do it tomorrow.

**Comment by ufenegga** [comment]
Thanks for your reply.  Yes, i was thinking that each dataset can have a different matrix, but then you can argue that each dataset has the same matrix, if each datasets represents a certain point of time, so it's okay to merge it.
I might have have some example with a leaflet layer in the next weeks, if u are interested, i can send it as a PR

**Comment by santilland** [comment]
Sounds like something that could be useful for other people, so if you find the time to add an example i would be very interested :) thanks again!

**Pull request merged**
